# Generated by Django 4.2.7 on 2025-08-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='check_interval',
            field=models.IntegerField(default=300),
        ),
    ]
