# Generated by Django 4.2.7 on 2025-08-19 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_website_check_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='UptimeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField()),
                ('response_time', models.FloatField()),
                ('status_code', models.IntegerField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uptime_checks', to='monitoring.website')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
